apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nodejs-prod-pvc
  namespace: prod1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-prod-deployment
  namespace: prod1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-prod
  template:
    metadata:
      labels:
        app: nodejs-prod
    spec:
      containers:
      - name: nodejs-prod
        image: khalidali07/nodejs-app:prod
        ports:
        - containerPort: 3000
        volumeMounts:
        - mountPath: "/usr/src/app/data"
          name: nodejs-storage
      volumes:
      - name: nodejs-storage
        persistentVolumeClaim:
          claimName: nodejs-prod-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-prod-svc
  namespace: prod1
spec:
  type: LoadBalancer
  selector:
    app: nodejs-prod
  ports:
    - port: 3000
      targetPort: 3000
